pid = "./run/cluster-demo-node-test.pid"
mode = "debug"
timezone = "Local"
shutdownMaxWaitTime = "5s"

[clusterDemo.debug]
addr = ":28004"

[cluster.node]
name = "lobby"
addr = ":19003"
codec = "json"
weight = 100
gameID = 1
version = "2.0.0"
serviceStatus = "test"
requestWorkers = 4
eventWorkers = 2
deliverTimeout = "3s"
mailboxTimeout = "3s"

[transport.rpcx.server]
addr = ":20003"

[registry.consul]
addr = "127.0.0.1:8500"
healthCheck = true
healthCheckInterval = 10
healthCheckTimeout = 5
heartbeatCheck = true
heartbeatCheckInterval = 10
deregisterCriticalServiceAfter = 30

[locate.redis]
addrs = ["127.0.0.1:6379"]
db = 0
prefix = "xbase:cluster-demo"

[log]
level = "info"
encoding = "console"
outputPaths = ["stdout"]
errorOutputPaths = ["stderr"]
stacktraceLevel = "error"
